### ISSUE TITLE
Thank you so much!!

### ISSUE THREAD

**Issue by GabrielSC92** [MathijsNL/WhatsappTime#3]
I couldn't find a way to thank you privately for this extension, but I wanted to say it anyway so here's a non-issue for you: this works perfectly!

It's keeping me sane to be back on 24h instead of 12h, so thanks again.

**Comment by MathijsNL** [comment]
You are welcome.

With big thanks to @Greenscreener who made the initial gist:
https://gist.github.com/Greenscreener/4422f5be36752bc720cbc7222fb73cdc
